// Builds the single-file engine consumed by tx. Output is committed so `dotnet build` works
// without npm; CI rebuilds it and fails if the committed file differs.
import { analyzeMetafile, build } from "esbuild";
import { readFileSync } from "node:fs";
import { builtinModules, createRequire } from "node:module";
import path from "node:path";
import { fileURLToPath } from "node:url";

const here = path.dirname(fileURLToPath(import.meta.url));
const require = createRequire(import.meta.url);
const outfile = path.resolve(here, "../../src/Tomix.App/Format/M/powerquery-engine.js");

function versionOf(pkg) {
    return JSON.parse(readFileSync(require.resolve(`${pkg}/package.json`), "utf8")).version;
}

const licenseFooter = `/*!
 * Bundled third-party code, each under the MIT License:
 *   @microsoft/powerquery-formatter ${versionOf("@microsoft/powerquery-formatter")} - Copyright (c) Microsoft Corporation.
 *   @microsoft/powerquery-parser ${versionOf("@microsoft/powerquery-parser")} - Copyright (c) Microsoft Corporation. All rights reserved.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy of this software
 * and associated documentation files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy, modify, merge, publish,
 * distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all copies or
 * substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING
 * BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM,
 * DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 */`;

// The parser bundles message templates for 42 locales; tx always runs it as en-US. Point every
// localized template at the en-US one so esbuild emits it once (~400 KB smaller).
const englishOnlyTemplates = {
    name: "english-only-templates",
    setup(b) {
        // Matches the import specifier ("./templates/template.de-DE.json"), which always uses "/".
        b.onResolve({ filter: /\/templates\/template\.[A-Za-z-]+\.json$/ }, (args) => ({
            path: path.join(args.resolveDir, "templates", "template.json"),
        }));
    },
};

// Anything that reaches for a Node built-in would break under the in-process host.
const noNodeBuiltins = {
    name: "no-node-builtins",
    setup(b) {
        const names = builtinModules.flatMap((m) => [m, `node:${m}`]);
        const filter = new RegExp(`^(${names.join("|")})$`);
        b.onResolve({ filter }, (args) => ({
            errors: [{ text: `Node built-in '${args.path}' imported by ${args.importer}` }],
        }));
    },
};

const result = await build({
    entryPoints: [path.join(here, "src/index.ts")],
    outfile,
    bundle: true,
    // Not `minify: true`: minifySyntax merges declarations into `let a = f(), b = await g()`, and
    // Jint re-runs `f()` when it resumes after the await (V8 does not), which breaks the parser.
    // Whitespace and identifier minification never merge statements. See the tripwire below.
    minifyWhitespace: true,
    minifyIdentifiers: true,
    format: "iife",
    platform: "neutral",
    mainFields: ["main", "module"],
    target: "es2022",
    charset: "utf8",
    legalComments: "eof",
    sourcemap: false,
    alias: {
        "grapheme-splitter": path.join(here, "src/shims/grapheme-splitter.cjs"),
        "performance-now": path.join(here, "src/shims/performance-now.cjs"),
    },
    define: {
        __FORMATTER_VERSION__: JSON.stringify(versionOf("@microsoft/powerquery-formatter")),
        __PARSER_VERSION__: JSON.stringify(versionOf("@microsoft/powerquery-parser")),
    },
    banner: {
        js: "// <auto-generated> Offline Power Query (M) engine for tx. Do not edit: regenerate with `npm ci && npm run build` in engines/powerquery. </auto-generated>",
    },
    // Upstream license headers are plain `//` comments, which legalComments does not keep.
    footer: { js: licenseFooter },
    plugins: [englishOnlyTemplates, noNodeBuiltins],
    logLevel: "info",
    metafile: process.env.ANALYZE === "1",
});

// Tripwire for the Jint await bug above: `, name = await` only appears when declarations were
// merged into one statement, by minifySyntax or by a dependency update that ships code that way.
const awaitAfterComma = readFileSync(outfile, "utf8").match(/,\s*[\w$]+\s*=\s*await\b/g);
if (awaitAfterComma) {
    console.error(
        `Bundle has ${awaitAfterComma.length} multi-declarator await(s) (e.g. '${awaitAfterComma[0]}'), ` +
            "which Jint evaluates incorrectly. Keep minifySyntax off or split the declarations.",
    );
    process.exit(1);
}

if (result.metafile) {
    console.log(await analyzeMetafile(result.metafile));
}
