using Tomix.Core.Results;

namespace Tomix.App.Completion;

/// <summary>
/// Generates shell completion scripts that ask the CLI for live suggestions.
/// Unsupported shells are rejected with exit code 2 (invalid arguments).
/// </summary>
public sealed class CompletionHandler
{
    private static readonly IReadOnlyList<string> SupportedShells =
        ["bash", "zsh", "powershell", "pwsh", "fish"];

    public TomixResult<CompletionResult> Generate(string shell, IReadOnlyList<string> commands)
    {
        var normalized = shell.Trim().ToLowerInvariant();

        if (!SupportedShells.Contains(normalized))
            return TomixResult<CompletionResult>.Fail(
                code: "TOMIX_COMPLETION_UNSUPPORTED_SHELL",
                message: UnsupportedShellMessage(shell),
                exitCode: 2);

        var script = normalized switch
        {
            "bash"       => Bash(),
            "zsh"        => Zsh(),
            "fish"       => Fish(),
            "powershell" => PowerShell(),
            "pwsh"       => PowerShell(),
            _            => ""
        };

        return TomixResult<CompletionResult>.Ok(new CompletionResult(
            normalized == "pwsh" ? "powershell" : normalized,
            script));
    }

    private static string Bash() =>
        """
        # tomix shell completion - generated by tx completion bash
        # Add to ~/.bashrc or ~/.bash_profile:
        #   eval "$(tx completion bash)"
        # Or append:
        #   tx completion bash >> ~/.bashrc

        _TOMIX_complete()
        {
            local completions
            completions=$(tx "[suggest:${COMP_POINT}]" "${COMP_LINE}" 2>/dev/null)
            local word="${COMP_WORDS[COMP_CWORD]}"
            local IFS=$'\n'
            local suggestions=($(compgen -W "$completions" -- "$word"))
            for i in "${!suggestions[@]}"; do
                suggestions[$i]="$(printf '%q' "${suggestions[$i]}")"
            done
            COMPREPLY=("${suggestions[@]}")
        }
        complete -o default -F _TOMIX_complete tx
        """;

    private static string Zsh() =>
        """
        # tomix shell completion - generated by tx completion zsh
        # Add to ~/.zshrc:
        #   eval "$(tx completion zsh)"
        # Or append:
        #   tx completion zsh >> ~/.zshrc

        _TOMIX_complete()
        {
            local completions
            completions=$(tx "[suggest:${CURSOR}]" "${BUFFER}" 2>/dev/null)
            local -a suggestions
            suggestions=(${(f)completions})
            compadd -a suggestions
        }
        compdef _TOMIX_complete tx
        """;

    private static string Fish() =>
        """
        # tomix shell completion - generated by tx completion fish
        # Save to: ~/.config/fish/completions/tx.fish
        #   tx completion fish > ~/.config/fish/completions/tx.fish

        function __TOMIX_complete
            set -l cl (commandline -p)
            set -l pos (commandline -C)
            tx "[suggest:$pos]" "$cl" 2>/dev/null
        end
        complete -c tx -f -a '(__TOMIX_complete)'
        """;

    private static string PowerShell() =>
        """
        # tomix shell completion - generated by tx completion powershell
        # Add to your PowerShell profile ($PROFILE):
        #   tx completion powershell | Out-String | Invoke-Expression
        # Or append:
        #   tx completion powershell >> $PROFILE

        # Register for all common invocation variants so tab completion works
        # whether the user types 'tx', '.\tx', 'tx.exe', or '.\tx.exe'.
        $__txNames = @('tx', 'tx.exe', '.\tx', '.\tx.exe')
        Register-ArgumentCompleter -Native -CommandName $__txNames -ScriptBlock {
            param($wordToComplete, $commandAst, $cursorPosition)
            $arguments = $commandAst.Extent.ToString().Replace('"', '\"')
            # Resolve the actual command the user typed (e.g. .\tx, tx.exe)
            $cmd = $commandAst.CommandElements[0].Extent.Text
            & $cmd "[suggest:$cursorPosition]" "$arguments" 2>$null | ForEach-Object {
                [System.Management.Automation.CompletionResult]::new($_, $_, 'ParameterValue', $_)
            }
        }
        """;

    private static string UnsupportedShellMessage(string shell)
        => $"Argument '{shell}' not recognized. Must be one of:{Environment.NewLine}" +
           string.Join(Environment.NewLine, SupportedShells.Select(s => $"\t'{s}'"));
}
