using Mdl.Core.Results;

namespace Mdl.App.Completion;

/// <summary>
/// Generates shell completion scripts that ask the CLI for live suggestions.
/// Unsupported shells are rejected with exit code 2 (invalid arguments).
/// </summary>
public sealed class CompletionHandler
{
    private static readonly IReadOnlyList<string> SupportedShells =
        ["bash", "zsh", "powershell", "pwsh", "fish"];

    public MdlResult<CompletionResult> Generate(string shell, IReadOnlyList<string> commands)
    {
        var normalized = shell.Trim().ToLowerInvariant();

        if (!SupportedShells.Contains(normalized))
            return MdlResult<CompletionResult>.Fail(
                code: "MDL_COMPLETION_UNSUPPORTED_SHELL",
                message: UnsupportedShellMessage(shell),
                exitCode: 2);

        var script = normalized switch
        {
            "bash"       => Bash(),
            "zsh"        => Zsh(),
            "fish"       => Fish(),
            "powershell" => PowerShell(),
            "pwsh"       => PowerShell(),
            _            => ""
        };

        return MdlResult<CompletionResult>.Ok(new CompletionResult(
            normalized == "pwsh" ? "powershell" : normalized,
            script));
    }

    private static string Bash() =>
        """
        # mdl shell completion - generated by mdl completion bash
        # Add to ~/.bashrc or ~/.bash_profile:
        #   eval "$(mdl completion bash)"
        # Or append:
        #   mdl completion bash >> ~/.bashrc

        _mdl_complete()
        {
            local completions
            completions=$(mdl "[suggest:${COMP_POINT}]" "${COMP_LINE}" 2>/dev/null)
            local word="${COMP_WORDS[COMP_CWORD]}"
            local IFS=$'\n'
            local suggestions=($(compgen -W "$completions" -- "$word"))
            for i in "${!suggestions[@]}"; do
                suggestions[$i]="$(printf '%q' "${suggestions[$i]}")"
            done
            COMPREPLY=("${suggestions[@]}")
        }
        complete -o default -F _mdl_complete mdl
        """;

    private static string Zsh() =>
        """
        # mdl shell completion - generated by mdl completion zsh
        # Add to ~/.zshrc:
        #   eval "$(mdl completion zsh)"
        # Or append:
        #   mdl completion zsh >> ~/.zshrc

        _mdl_complete()
        {
            local completions
            completions=$(mdl "[suggest:${CURSOR}]" "${BUFFER}" 2>/dev/null)
            local -a suggestions
            suggestions=(${(f)completions})
            compadd -a suggestions
        }
        compdef _mdl_complete mdl
        """;

    private static string Fish() =>
        """
        # mdl shell completion - generated by mdl completion fish
        # Save to: ~/.config/fish/completions/mdl.fish
        #   mdl completion fish > ~/.config/fish/completions/mdl.fish

        function __mdl_complete
            set -l cl (commandline -p)
            set -l pos (commandline -C)
            mdl "[suggest:$pos]" "$cl" 2>/dev/null
        end
        complete -c mdl -f -a '(__mdl_complete)'
        """;

    private static string PowerShell() =>
        """
        # mdl shell completion - generated by mdl completion powershell
        # Add to your PowerShell profile ($PROFILE):
        #   mdl completion powershell | Out-String | Invoke-Expression
        # Or append:
        #   mdl completion powershell >> $PROFILE

        # Register for all common invocation variants so tab completion works
        # whether the user types 'mdl', '.\mdl', 'mdl.exe', or '.\mdl.exe'.
        $__mdlNames = @('mdl', 'mdl.exe', '.\mdl', '.\mdl.exe')
        Register-ArgumentCompleter -Native -CommandName $__mdlNames -ScriptBlock {
            param($wordToComplete, $commandAst, $cursorPosition)
            $arguments = $commandAst.Extent.ToString().Replace('"', '\"')
            # Resolve the actual command the user typed (e.g. .\mdl, mdl.exe)
            $cmd = $commandAst.CommandElements[0].Extent.Text
            & $cmd "[suggest:$cursorPosition]" "$arguments" 2>$null | ForEach-Object {
                [System.Management.Automation.CompletionResult]::new($_, $_, 'ParameterValue', $_)
            }
        }
        """;

    private static string UnsupportedShellMessage(string shell)
        => $"Argument '{shell}' not recognized. Must be one of:{Environment.NewLine}" +
           string.Join(Environment.NewLine, SupportedShells.Select(s => $"\t'{s}'"));
}
