<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Tomix.Cli.Tests" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Page\index.html" LogicalName="Tomix.Ui.Page.index.html" />
  </ItemGroup>

  <PropertyGroup>
    <IsAotCompatible>true</IsAotCompatible>
  </PropertyGroup>

</Project>
