using System.Text.Json;
using Tomix.App.Format.M;

namespace Tomix.App.Tests;

/// <summary>
/// The M engine bundle is generated by <c>engines/powerquery</c> and committed. These guard that it
/// ships inside Tomix.App and still matches the pinned npm versions, without needing npm.
/// </summary>
public sealed class PowerQueryEngineBundleTests
{
    [Fact]
    public void Load_ReturnsEmbeddedBundleThatDefinesTheEngineGlobal()
    {
        var bundle = PowerQueryEngineBundle.Load();

        Assert.Contains($"globalThis.{PowerQueryEngineBundle.GlobalName}=", bundle);
    }

    [Theory]
    [InlineData("@microsoft/powerquery-formatter")]
    [InlineData("@microsoft/powerquery-parser")]
    public void Load_BundleCarriesThePinnedPackageVersion(string package)
    {
        using var manifest = JsonDocument.Parse(File.ReadAllText(RepoPaths.Combine("engines", "powerquery", "package.json")));
        var pinned = manifest.RootElement.GetProperty("dependencies").GetProperty(package).GetString();

        Assert.Contains($"{package} {pinned} - Copyright", PowerQueryEngineBundle.Load());
    }
}
