/// Standard date dimension marked as the model's date table so time-intelligence functions (YTD, prior period, etc.) work. Contains one row per day with calendar attributes (Year, Period, Month).
table Date
	lineageTag: 862318f7-551a-4379-ac89-8647a25f938c
	dataCategory: Time

	/// Calendar date. Grain of the Date table (one row per day).
	column Date
		dataType: dateTime
		isHidden
		isKey
		formatString: General Date
		lineageTag: b5041ac2-a830-4938-a8dd-606ddb11c145
		summarizeBy: none
		sourceColumn: Date

		annotation SummarizationSetBy = Automatic

	/// Calendar year of the date.
	column Year
		dataType: int64
		lineageTag: f8b2d0a9-b11c-4631-9255-1c2ad4dc7a4a
		summarizeBy: sum
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Fiscal/calendar period number (1-12) used to sort the Month column into calendar order.
	column Period
		dataType: int64
		lineageTag: de5281a9-3ef1-4183-a58e-5ad88c16cf13
		summarizeBy: sum
		sourceColumn: Period

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Three-letter month name (Jan, Feb, ...). Sorted by Period so visuals show months in calendar order rather than alphabetically.
	column Month = Format([Date],"MMM")
		lineageTag: 6e3a150b-8173-440d-af99-657155644df0
		summarizeBy: none
		sortByColumn: Period

		annotation SummarizationSetBy = Automatic

	partition Date = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\mad\Dropbox\Work\Obvience\IP\IT\Data\Clean\Data.xlsx"), null, true),
				    Sheet = Source{[Item="Date",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(Sheet),
				    #"Renamed Columns" = Table.RenameColumns(#"Promoted Headers", {{"Date", "Date"}, {"Year", "Year"}, {"Period", "Period"}}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Renamed Columns", {{"Date", type datetime}, {"Year", Int64.Type}, {"Period", Int64.Type}})
				 in
				    #"Changed Type"

