/// Use to filter or group visuals by store, chain, store format, district manager, or when the store opened.
table Store
	lineageTag: 0862204f-8f7e-49e5-b8ef-9ec0e9d8569d

	/// Average selling area (square feet) across the stores in the current selection.
	measure 'Average Selling Area Size' = AVERAGE([SellingAreaSize])
		formatString: #,0
		displayFolder: Size Metrics
		lineageTag: d4d8be7f-1baa-48a1-bf61-f2647049ffa3

	/// Number of stores newly opened in the current selection. Compare against [New Stores Target] for goal tracking.
	measure 'New stores' = CALCULATE(COUNTA([Store type]), FILTER(ALL(Store), [Store type]="New Store"))
		formatString: #,0
		displayFolder: Store Counts
		lineageTag: ac544d84-fd6b-475b-973a-69c387496cca

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Target for new store openings. Use as a comparison value against [New Stores].
	measure 'New stores target' = 14
		formatString: #,0
		displayFolder: Store Counts
		lineageTag: 4087871e-363a-469e-b45d-707dd02bfa89

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Total number of stores in the current selection. Use on cards or as a denominator for per-store metrics.
	measure Stores = COUNTA([Store name and number])
		formatString: #,0
		displayFolder: Store Counts
		lineageTag: 2e7df479-c5cd-410e-905a-b89480f7f9f8

	/// Number of stores currently open. Use on cards or as a filter denominator.
	measure 'Open stores' = COUNTA([Opening date])
		formatString: #,0
		displayFolder: Store Counts
		lineageTag: 30cee895-9cf3-4f03-82c9-b0295fc9ff14

	/// Count of stores with a recorded open date.
	measure 'Number of opening dates' = COUNTA('Store'[Opening date])
		formatString: #,0
		displayFolder: Store Counts
		lineageTag: c5c2edee-1f9b-42c2-a823-052a180088a6

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column LocationID
		dataType: int64
		isHidden
		isKey
		lineageTag: d88dc5fb-f521-480c-83ce-7afc24fb5124
		summarizeBy: none
		sourceColumn: LocationID

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'City Name'
		dataType: string
		isHidden
		lineageTag: 78d437bf-c366-4939-a6ba-f647a6fc185f
		dataCategory: City
		summarizeBy: none
		sourceColumn: City Name

		annotation SummarizationSetBy = Automatic

	/// Slice or group visuals by state/territory of the store.
	column Territory
		dataType: string
		displayFolder: Location
		lineageTag: d65e7eb7-1bad-4eba-8b5c-9d2a8099beee
		dataCategory: StateOrProvince
		summarizeBy: none
		sourceColumn: Territory

		annotation SummarizationSetBy = Automatic

	/// Slice or group visuals by store postal/ZIP code, or use for map visuals.
	column 'Postal code'
		dataType: string
		displayFolder: Location
		lineageTag: 64a19c9f-97ec-4c28-9491-d7e9c0908460
		dataCategory: PostalCode
		summarizeBy: none
		sourceColumn: Postal code

		annotation SummarizationSetBy = Automatic

		annotation __PBI_SemanticLinks = [{"LinkTarget":{"TableName":"Item","TableItemName":"Category (clusters) 2","ObjectType":4},"LinkType":"UsedInGroup"}]

	/// Date each store opened. Filter by open-date range to isolate new vs. established stores, or plot on a timeline.
	column 'Opening date'
		dataType: dateTime
		formatString: dd-mmm-yyyy
		displayFolder: Opening
		lineageTag: c7615f0e-a376-4b14-959a-fae6f7f78072
		summarizeBy: none
		sourceColumn: Opening date

		annotation SummarizationSetBy = Automatic

	/// Store selling area in square feet. Sum or average on cards; use as scatter/bubble size for area-vs-sales analysis.
	column SellingAreaSize
		dataType: int64
		isHidden
		displayFolder: Store Info
		lineageTag: 25dfc9ea-95a3-49c6-a17d-ab892084ed28
		summarizeBy: sum
		sourceColumn: SellingAreaSize

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column DistrictName
		dataType: string
		isHidden
		lineageTag: 01221944-8dcd-4885-928a-998edf602727
		summarizeBy: none
		sourceColumn: DistrictName

		annotation SummarizationSetBy = Automatic

	/// Store name. Use in table/matrix rows or bar-chart axes for per-store analysis.
	column Name
		dataType: string
		displayFolder: Store Info
		lineageTag: 47196cfa-ca7a-4529-a65f-0b22c05b1f8d
		summarizeBy: none
		sourceColumn: Name

		annotation SummarizationSetBy = Automatic

	/// Store number combined with store name. Use in table/matrix rows when you want both the ID and name in one label.
	column 'Store name and number'
		dataType: string
		displayFolder: Store Info
		lineageTag: 9b6ad4d6-64d5-46b0-bd6b-f5acca41eafb
		tableDetailPosition: 0
		isDefaultLabel
		summarizeBy: none
		sourceColumn: Store name and number

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	/// Unique store number identifier.
	column StoreNumber
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 47dc55a3-0215-435d-9920-c16ada4eb4ab
		summarizeBy: none
		sourceColumn: StoreNumber

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// City where the store is located. Use on slicers, map visuals, or as a group-by column.
	column City = [City Name] & ", "&[Territory]
		displayFolder: Location
		lineageTag: 9916b52e-c253-4676-ad00-2ce73b864c3b
		dataCategory: City
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	/// Retail chain the store belongs to. Use on axes or slicers to compare chains.
	column Chain
		dataType: string
		displayFolder: Store Info
		lineageTag: 37259bfb-911c-4568-85ef-91a69d351cf5
		summarizeBy: none
		sourceColumn: Chain

		annotation SummarizationSetBy = Automatic

	/// District manager assigned to the store. For district-level rollups prefer District[DM] instead.
	column DM
		dataType: string
		isHidden
		displayFolder: Management
		lineageTag: 03782db7-df58-4363-94d2-38a6eabad75e
		summarizeBy: none
		sourceColumn: DM

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	/// Photo of the district manager (DM).
	column DM_Pic
		dataType: string
		isHidden
		lineageTag: 2f3622ba-7ee7-45fd-8d23-2319527679c2
		dataCategory: ImageUrl
		summarizeBy: none
		sourceColumn: DM_Pic

		annotation SummarizationSetBy = Automatic

	column DistrictID
		dataType: int64
		isHidden
		lineageTag: 9f76763d-0f5b-42ab-875c-90aac4331d9d
		summarizeBy: none
		sourceColumn: DistrictID

	/// Year the store opened. Use as a slicer or axis to view stores by opening cohort.
	column 'Opening year' = YEAR([Opening date])
		formatString: 0
		displayFolder: Opening
		lineageTag: b9328ca3-4eff-4bbe-b55b-1665de13ea35
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Store format (Flagship, Standard, Outlet, etc.). Use on axes, slicers, or as a legend to compare formats.
	column 'Store type' = IF([Opening year]=2014, "New Store", "Same Store")
		displayFolder: Store Info
		lineageTag: 307f2a8b-8a05-4ccb-846f-5c417b528f57
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

		annotation __PBI_SemanticLinks = [{"LinkTarget":{"TableName":"Item","TableItemName":"Category (clusters) 2","ObjectType":4},"LinkType":"UsedInGroup"}]

	/// Numeric month the store opened (used to sort Open Month).
	column 'Open Month No' = MONTH([Opening date])
		isHidden
		formatString: 0
		displayFolder: Opening
		lineageTag: 448890ad-ad5e-46aa-ac6b-3c5f11017dad
		summarizeBy: none

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Calendar month each store opened. Use on axes or slicers — already sorts chronologically.
	column 'Opening month' = FORMAT([Opening date], "MMM")
		displayFolder: Opening
		lineageTag: ec6705ae-e510-4e4f-adc3-385e3b2667c0
		summarizeBy: none
		sortByColumn: 'Open Month No'

		annotation SummarizationSetBy = Automatic

	partition Store = m
		mode: import
		source =
				let
				    Source = Sql.Database(".", "RetailBIDW", [Query="select * from ip.retail.StoreDim"]),
				    #"Renamed Columns" = Table.RenameColumns(Source, {{"LocationID", "LocationID"}, {"City", "City Name"}, {"Territory", "Territory"}, {"PostalCode", "PostalCode"}, {"OpenDate", "OpenDate"}, {"SellingAreaSize", "SellingAreaSize"}, {"DistrictName", "DistrictName"}, {"Name", "Name"}, {"StoreNumberName", "StoreNumberName"}, {"StoreNumber", "StoreNumber"}, {"Chain", "Chain"}, {"DM", "DM"}, {"DM_Pic", "DM_Pic"}, {"DistrictID", "DistrictID"}}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Renamed Columns", {{"LocationID", Int64.Type}, {"City Name", type text}, {"Territory", type text}, {"PostalCode", type text}, {"OpenDate", type datetime}, {"SellingAreaSize", Int64.Type}, {"DistrictName", type text}, {"Name", type text}, {"StoreNumberName", type text}, {"StoreNumber", Int64.Type}, {"Chain", type text}, {"DM", type text}, {"DM_Pic", type text}, {"DistrictID", Int64.Type}}),
				    #"Renamed Columns1" = Table.RenameColumns(#"Changed Type",{{"StoreNumberName", "Store name and number"}, {"OpenDate", "Opening date"}, {"PostalCode", "Postal code"}})
				in
				    #"Renamed Columns1"

	annotation __PBI_SemanticLinks = [{"LinkTarget":{"TableName":"Item","TableItemName":"Category (clusters) 2","ObjectType":4},"LinkType":"UsedInGroup"}]

