table Sales

	measure 'Total Sales' = SUM ( Sales[Amount] )

	measure 'Order Count' = COUNTROWS(Sales)

	measure 'Avg Sale' = AVERAGE(Sales[Amount])

	measure 'Distinct Customers' = DISTINCTCOUNT(Sales[CustomerID])

	column SaleID
		dataType: int64
		sourceColumn: SaleID

	column CustomerID
		dataType: int64
		sourceColumn: CustomerID

	column ProductID
		dataType: int64
		sourceColumn: ProductID

	column Amount
		dataType: decimal
		sourceColumn: Amount

	partition Sales = m
		mode: import
		source = let Source = #table({"SaleID", "CustomerID", "ProductID", "Amount"}, {}) in Source

